name: Compile
run-name: ${{ github.actor }} is start compile ğŸ¥³
on: [ push, pull_request ]
jobs:
  Compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, world! This is UXU product
  Install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install.yml
  Testing:
    name: Testing
    needs: [Install]
    runs-on: ubuntu-latest
    steps:
      # This step references the directory that contains the action with testing lint.
      - uses: ./.github/actions/lint
  Build:
    name: Build project
    needs: [ Install, Testing ]
    runs-on: ubuntu-latest
    steps:
    # This step references the directory that contains the action with testing lint.
    - uses: ./.github/actions/lint
